services:
  nostr-rs-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "8080:8080"
    volumes:
      - ./dev/data/nostr-rs-relay:/usr/src/app/data
      - ./dev/nostr-rs-relay-config.toml:/usr/src/app/config.toml
    environment:
      - RUST_LOG=info
    restart: unless-stopped
  blossom:
    image: ghcr.io/hzrd149/blossom-server:master
    build: .
    volumes:
      - ./dev/data/blossom-ts-server:/app/data
      - ./dev/blossom-server-ts-config.yml:/app/config.yml
    ports:
      - 3000:3000
    restart: unless-stopped
  strfry-nostr-relay:
    image: dockurr/strfry:latest
    volumes:
      - ./dev/strfry.conf:/etc/strfry.conf
      - ./dev/data/strfry-db:/app/strfry-db
    ports:
      - "7777:7777"
    restart: unless-stopped
